"""Canonical damage labels shared by Aristotel, condition model, and MoE."""

DAMAGE_CLEAN = "clean"
DAMAGE_LIGHT_CUT = "light_cut"
DAMAGE_LIGHT_BLUR = "light_blur"
DAMAGE_SCANNER_NOISE = "scanner_noise"
DAMAGE_LIGHT_EROSION = "light_erosion"
DAMAGE_INK_OVERLAP = "ink_overlap"
DAMAGE_STAMP_INTERFERENCE = "stamp_interference"
DAMAGE_BLEED_THROUGH = "bleed_through"
DAMAGE_EDGE_CROP_LOSS = "edge_crop_loss"
DAMAGE_THRESHOLD_FAILURE = "threshold_failure"
DAMAGE_COMPRESSION_ARTIFACTS = "compression_artifacts"
DAMAGE_UNKNOWN = "unknown"

DAMAGE_LABELS = [
    DAMAGE_CLEAN,
    DAMAGE_LIGHT_CUT,
    DAMAGE_LIGHT_BLUR,
    DAMAGE_SCANNER_NOISE,
    DAMAGE_LIGHT_EROSION,
    DAMAGE_INK_OVERLAP,
    DAMAGE_STAMP_INTERFERENCE,
    DAMAGE_BLEED_THROUGH,
    DAMAGE_EDGE_CROP_LOSS,
    DAMAGE_THRESHOLD_FAILURE,
    DAMAGE_COMPRESSION_ARTIFACTS,
]

REPAIR_NEEDED_DAMAGE_LABELS = {
    DAMAGE_LIGHT_CUT,
    DAMAGE_LIGHT_EROSION,
    DAMAGE_EDGE_CROP_LOSS,
    DAMAGE_THRESHOLD_FAILURE,
}

UNCERTAIN_DAMAGE_LABELS = {
    DAMAGE_LIGHT_BLUR,
    DAMAGE_SCANNER_NOISE,
    DAMAGE_INK_OVERLAP,
    DAMAGE_STAMP_INTERFERENCE,
    DAMAGE_BLEED_THROUGH,
    DAMAGE_COMPRESSION_ARTIFACTS,
}

ALL_DAMAGE_LABELS = DAMAGE_LABELS + [DAMAGE_UNKNOWN]